# Generated by Django 4.0.2 on 2022-05-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='short_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
