# Generated by Django 4.0.5 on 2022-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_articles_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='avatar',
            field=models.ImageField(null=True, upload_to='article_images'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
