# Generated by Django 4.0.5 on 2022-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_articles_avatar_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/article_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_avatar',
            field=models.ImageField(default='images/profile_pictures/avatar.jpg', upload_to='images/profile_pictures'),
        ),
    ]
