# Generated by Django 4.0.5 on 2022-07-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customuser_bio_alter_articles_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='classname',
        ),
    ]
